language: node_js
node_js:
  - 10
  - 12
  - node
before_script:
  - npm install -g gulp-cli
script:
  - gulp
  - gulp example
  - npm test
  - npm run report-coverage
cache:
  directories:
    - node_modules
